[package]
name = "alumet-api-dynamic"
version = "0.1.0"
edition = "2021"
description = "Rust sugar on top of the C API, to make dynamic ALUMET plugins in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
