[report]
out = ["Html", "Xml", "Lcov"]
output-dir = "target/tarpaulin"

[test]
skip-clean = true
include-tests = true
exclude = ["test-dynamic-plugins", "test-dynamic-plugin-c", "test-dynamic-plugin-rust"]
follow-exec = true
workspace = true
timeout = "5m"
all-features = true