[workspace]
resolver = "2"
members = [
    "alumet",
    "alumet-api-dynamic",
    "alumet-api-macros",
    "app-agent",
    "plugin-nvidia",
    "plugin-rapl",
    "test-dynamic-plugin-rust",
    "test-dynamic-plugins",
]
