[package]
name = "test-static-plugin"
version = "0.1.0"
edition = "2021"
description = "Example of a static ALUMET plugin, written as a library."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alumet = { path = "../alumet" }
alumet-api-macros = { path = "../alumet-api-macros" }