[package]
name = "app-agent"
version = "0.1.0"
edition = "2021"
description = "Metric collector agent to install on each node."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alumet = { path = "../alumet" }
anyhow = "1.0.79"
env_logger = "0.11.2"
log = "0.4.20"
plugin-csv = { version = "0.1.0", path = "../plugin-csv" }
plugin-rapl = { version = "0.2.0", path = "../plugin-rapl" }
plugin-socket-control = { version = "0.1.0", path = "../plugin-socket-control" }
toml = "0.8.12"
