[package]
name = "plugin-socket-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alumet = { path = "../alumet" }
anyhow = "1.0.82"
log = "0.4.21"
tokio = { version = "1.37.0", features = ["net", "io-util"] }
tokio-util = "0.7.10"
